#SALES PREDICTION USING PYTHON

## Importing the Dataset.

In [2]:
import pandas as pd
df = pd.read_csv("/content/Advertising.csv")

## Inspecting the Dataset

In [3]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [5]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [6]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [10]:
df.dropna(inplace = True)

In [11]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

## Creating X and y (Independent and dependent variables)

In [15]:
X = df[["TV", "Radio", "Newspaper"]].to_numpy()

In [17]:
X.shape

(200, 3)

In [19]:
y = df["Sales"].to_numpy()

## Creating Train Test Splits

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 42, test_size = 0.2)
len(X_train), len(X_test), len(y_train), len(y_test)

(160, 40, 160, 40)

## Creating Dense Model:

In [24]:
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation = "relu"),
    tf.keras.layers.Dense(64, activation = "relu"),
    tf.keras.layers.Dense(1, activation = "linear"),
])

model.compile(loss = "mae",
              optimizer = tf.keras.optimizers.Adam(),
              metrics = ["mae", "mse"])

model.fit(X_train,
          y_train,
          epochs = 20,
          validation_data = (X_test, y_test))

Epoch 1/20
5/5 [==============================] - 1s 67ms/step - loss: 21.8211 - mae: 21.8211 - mse: 647.8046 - val_loss: 3.8331 - val_mae: 3.8331 - val_mse: 20.5949
Epoch 2/20
5/5 [==============================] - 0s 17ms/step - loss: 7.8106 - mae: 7.8106 - mse: 104.0867 - val_loss: 7.4101 - val_mae: 7.4101 - val_mse: 94.6833
Epoch 3/20
5/5 [==============================] - 0s 12ms/step - loss: 5.4884 - mae: 5.4884 - mse: 58.5945 - val_loss: 4.1813 - val_mae: 4.1813 - val_mse: 22.5507
Epoch 4/20
5/5 [==============================] - 0s 15ms/step - loss: 4.3193 - mae: 4.3193 - mse: 24.8415 - val_loss: 3.4172 - val_mae: 3.4172 - val_mse: 15.7923
Epoch 5/20
5/5 [==============================] - 0s 11ms/step - loss: 3.2922 - mae: 3.2922 - mse: 18.4287 - val_loss: 3.3875 - val_mae: 3.3875 - val_mse: 18.9320
Epoch 6/20
5/5 [==============================] - 0s 11ms/step - loss: 2.6766 - mae: 2.6766 - mse: 10.9293 - val_loss: 3.1176 - val_mae: 3.1176 - val_mse: 13.2633
Epoch 7/20
5/5 [==

## Evaluating the model on test Dataset

In [25]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 9ms/step - loss: 1.7889 - mae: 1.7889 - mse: 4.9877


[1.7888939380645752, 1.7888939380645752, 4.987725257873535]

## Making preds on test dataset

In [26]:
model_preds = model.predict(X_test)
model_preds[:10]

2/2 [==============================] - 0s 6ms/step


array([[17.865839 ],
       [23.688494 ],
       [23.782465 ],
       [ 6.302439 ],
       [25.199337 ],
       [13.422132 ],
       [23.766981 ],
       [ 6.1256943],
       [12.698037 ],
       [15.776511 ]], dtype=float32)

## Comapring the mae %

In [29]:
# Individual pred comparison
tf.keras.metrics.mean_absolute_percentage_error(y_true = y_test,
                                                y_pred = model_preds)

<tf.Tensor: shape=(40,), dtype=float32, numpy=
array([ 65.17779 , 106.70818 , 107.50592 ,  47.26305 , 119.67156 ,
        41.08736 , 107.37406 ,  48.321335,  37.784016,  52.973892,
        41.56885 ,  44.65044 ,  68.62998 ,  68.516495,  36.203186,
        34.411118,  61.12231 ,  60.96856 ,  33.69621 ,  81.10096 ,
        95.830124,  72.838615,  32.95493 , 110.32035 ,  45.966896,
        56.19566 , 103.56265 ,  33.964478,  36.66441 ,  64.95859 ,
        33.60582 ,  34.249107, 110.4882  ,  35.21672 ,  72.25222 ,
        95.461365,  37.856388,  99.79748 ,  32.962097,  65.88147 ],
      dtype=float32)>

In [31]:
# Overall pred comparison rate
tf.keras.metrics.mean_absolute_percentage_error(y_true = tf.squeeze(y_test),
                                                y_pred = tf.squeeze(model_preds))

<tf.Tensor: shape=(), dtype=float32, numpy=15.836847>